// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDYUQg_8bNHSd5mJWHTYvBycejJ1R9z4N8",
    authDomain: "fooddeliverapp-976fe.firebaseapp.com",
    projectId: "fooddeliverapp-976fe",
    storageBucket: "fooddeliverapp-976fe.appspot.com",
    messagingSenderId: "1037370591895",
    appId: "1:1037370591895:web:d5463cc0ffb4343fa9f7d2",
    measurementId: "G-DDM4G1354W",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1JEVsvJoSH6BG_tWPvLnrK1sLCZvIAi8',
    appId: '1:1037370591895:android:5ff5fdfe71b3c10ca9f7d2',
    messagingSenderId: '445557739968',
    projectId: 'fooddeliverapp-976fe',
    storageBucket: 'fooddeliverapp-976fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-p1IKsCFhuqU3gQrkDq0RtguwK6Etto',
    appId: '1:1037370591895:ios:93db2a245d93377ba9f7d2',
    messagingSenderId: '1037370591895',
    projectId: 'fooddeliverapp-976fe',
    storageBucket: 'fooddeliverapp-976fe.appspot.com',
    iosBundleId: 'com.example.fooddeliverapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbo3rxrBZca5MNhvM3gydmbJrrR1FLkHU',
    appId: '1:445557739968:ios:7bec7c363fa3abd71bf825',
    messagingSenderId: '445557739968',
    projectId: 'fooddeliverapp-976fe',
    storageBucket: 'fooddeliverapp-976fe.appspot.com',
    iosBundleId: 'com.example.inclassactivity13.RunnerTests',
  );
}
